### ISSUE TITLE
image preview not working

### ISSUE THREAD

**Issue by Kemphire** [savedra1/clipse#119] opened 2024-08-11 19:41 UTC
so i downloaded clipse using go, i'm able to use text, but when i copy image it only shows the path of image not the image itself
![image](https://github.com/user-attachments/assets/5945a099-1fe7-4541-a9f0-22e9f2ea8cf5)

**Comment by savedra1** [comment] 2024-08-11 21:24
Hi @Kemphire :wave: 

If the image preview only shows the path to the file as a string, this could mean there was a problem with the file being being saved to the temporary location (specified in the `~/.config/clipse/config.json` file) or that the file had been deleted/renamed since it was saved.  

If you check the directory containing the temporary image files, do you see the image(s) in there? If not, is there something that could be deleting/editing the files after they are saved, or is there something preventing the files to be saved? 

If there is an error when trying to store the image data, something should be logged to your the log file specified in '~/.config/clipse/config.json` .

let me know how it goes. Thanks!

**Comment by Kemphire** [comment] 2024-08-14 04:33
image preview is working but, it's so to blurry to understand, btw i'm using kitty is there anyway i can use kitty's protocol icat for image preview

![screenshot_2024-08-14_10-02-18](https://github.com/user-attachments/assets/6f07a049-2943-4041-bc7c-13e3cb2e0301)

**Comment by savedra1** [comment] 2024-08-14 08:50
I see @Kemphire thanks for clarifying. 

Implementing `icat` for `kitty` terminal has been raised in #117 as a feature request. The image preview quality cannot be improved until that's been worked on so I will close this issue as a duplicate of #117 for now.

Thanks for the issue!

**Closed by savedra1** 2024-08-14 08:50 UTC

**Comment by Marrieto** [comment] 2024-08-17 19:59
Thanks for the issue @Kemphire, I was just about to raise the same problem! :smile_cat:
