### ISSUE TITLE
[hyprland] issue with Persistent history

### ISSUE THREAD

**Issue by shadowelite-sec** [savedra1/clipse#114] opened 2024-07-29 17:49 UTC
When I try to copy text from applications, I can only paste the text if the application window is still open. However, the history of copied text is saved. I can select the text from history, and even if I close the application, the text can be pasted.

**Comment by savedra1** [comment] 2024-07-30 16:23
Hi @shadowelite-sec :wave: 

Thanks for raising this.

Can I ask what applications are you copying from? I'm wondering if this behaviour is caused by the application rather than by the clipse program. Have you confirmed that you don't get this behaviour when the clipse binary is not running?

It would also be useful to know what desktop environment you are on (wayland/x11) and which clipboard utility (wl-clipboard/xclip etc).

**Comment by shadowelite-sec** [comment] 2024-07-30 16:56
> Hi @shadowelite-sec 👋
> 
> Thanks for raising this.
> 
> Can I ask what applications are you copying from? I'm wondering if this behaviour is caused by the application rather than by the clipse program. Have you confirmed that you don't get this behaviour when the clipse binary is not running?
> 
> It would also be useful to know what desktop environment you are on (wayland/x11) and which clipboard utility (wl-clipboard/xclip etc). **EDIT**: just noticed the `[hyprland]` in the issue title so assuming Wayland and wl-clipboard 😄

It's happening to all xwayland and wayland applications

I am not sure maybe it's is related to https://github.com/hyprwm/Hyprland/issues/6725#issuecomment-2254670283

**Comment by savedra1** [comment] 2024-07-31 07:51
Yeah it deffo could be related to that. I guess the quickest way to know for sure is check if it still happens after running `clipse --kil`

**Comment by shadowelite-sec** [comment] 2024-07-31 08:20
> Yeah it deffo could be related to that. I guess the quickest way to know for sure is check if it still happens after running `clipse --kil`

Yes , it happens

**Comment by savedra1** [comment] 2024-08-01 11:10
Thanks for confirming @shadowelite-sec 

I'll close this issue then but will keep an eye out for that Hyprland bug :eyes:

**Closed by savedra1** 2024-08-01 11:10 UTC
